future: true
filter_optimize:
  enable: true
  versioning: false
  css:
    minify: true
    excludes: null
    delivery:
      - "@fortawesome/fontawesome-free"
      - fonts.googleapis.com
    inlines:
      - css/main.css
  js:
    minify: true
    excludes: null
    remove_comments: false
  html:
    minify: true
    excludes: null
  priority: 12
permalink_defaults: null
index_generator:
  path: ""
  per_page: 15
  order_by: -date
  pagination_dir: page
deploy: null
include: null
titlecase: false
date_format: YYYY-MM-DD
filename_case: 0
pagination_dir: page
tag_dir: tags
default_layout: post
time_format: HH:mm:ss
theme: next
source_dir: source
prismjs:
  enable: false
  preprocess: true
keywords: blog, oi
author: cn_ryh
new_post_name: :title.md
permalink: :title/
category_dir: categories
i18n_dir: :lang
relative_link: false
pretty_urls:
  trailing_index: true
  trailing_html: true
external_link:
  enable: true
  field: site
  exclude: ""
markdown:
  preset: 'default'
  render:
    html: true
    xhtmlOut: true
    langPrefix: 'language-'
    breaks: true
    linkify: true
    typographer: true
    quotes: '“”‘’'
  enable_rules:
  disable_rules:
  plugins:
    - markdown-it-mark
    - markdown-it-container
    - markdown-it-emoji
    - markdown-it-footnote
  anchors:
    level: 2
    collisionSuffix: ''
    permalink: false
    permalinkClass: 'header-anchor'
    permalinkSide: 'left'
    permalinkSymbol: '¶'
    case: 0
    separator: '-'
  images:
    lazyload: false
    prepend_root: false
    post_asset: false
  inline: false  # https://markdown-it.github.io/markdown-it/#MarkdownIt.renderInline
url: https://blog.cnryh.cn

archive_dir: archives
per_page: 0
ignore: null
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace: ""
  wrap: true
  hljs: false
sitemap:
  path: sitemap.xml
skip_render:
  - admin/config.yml
  - adarkroom/*
  - mbti/*
public_dir: public
tag_map: null
subtitle: cn_ryh's Blog
title: cn_ryh's Home
language: zh-CN
updated_option: mtime
meta_generator: true
timezone: Asia/Shanghai
exclude: null
since: 2024
render_drafts: false
category_map: null
code_dir: downloads/code
default_category: uncategorized
post_asset_folder: false
description: 离开这里了

lazyload:
  enable: true
  onlypost: false # optional
  loadingImg: # optional eg ./images/loading.gif
  isSPA: false # optional
  preloadRatio: 3 # optional, default is 1
